import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { getMessages } from "next-intl/server";
import MuiThemeProvider from "../../configs/mui/MuiThemeProvider";
import ClientScriptLoader from "../components/ClientScriptLoader";

import "../../public/css/animate.min.css";
import "../../public/css/bootstrap-icons.css";
import "../../public/css/bootstrap.min.css";
import "../../public/css/flaticon.css";
import "../../public/css/fontawesome.min.css";
import "../../public/css/magnific-popup.min.css";
import "../../public/css/meanmenu.css";
import "../../public/css/owl.carousel.min.css";
import "../../public/css/swiper.min.css";
import "../../public/css/vegas.min.css";
import "../../public/css/responsive.css";
import "../../public/css/style.css";
import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import CopyRight from "../components/layout/CopyRight";
import GoTop from "../components/layout/GoTop";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html lang="en">
      <NextIntlClientProvider messages={messages}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <MuiThemeProvider>
            <ClientScriptLoader />
            <Navbar />
            {children}
            <Footer />
            <CopyRight />
            <GoTop />
          </MuiThemeProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
